<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Weda.SubNode.Core\Weda.SubNode.Core.csproj" />
    <ProjectReference Include="..\..\src\Weda.SubNode.Host\Weda.SubNode.Host.csproj" />
    <ProjectReference Include="..\..\src\Weda.SubNode.Abstractions\Weda.SubNode.Abstractions.csproj" />
    <ProjectReference Include="..\Weda.SubNode.TestBase\Weda.SubNode.TestBase.csproj" />
  </ItemGroup>

</Project>
