services:
  wise-4012-isensing:
    build:
      context: ../..
      dockerfile: examples/mqtt-isensing-wise4012/Dockerfile
    volumes:
      - ./devicecfg.json:/app/devicecfg.json:ro
      - ./systemcfg.json:/app/systemcfg.json:ro
      - ./customcfg.json:/app/customcfg.json:ro
      - ./appsettings.json:/app/appsettings.json:ro
      - ./weda-data:/app/.weda
    network_mode: host
    restart: unless-stopped
