<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\examples\http-stock-quotes\HttpStockQuotes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DTDLParser" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

</Project>
