<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Weda.SubNode.Host\Weda.SubNode.Host.csproj" />
    <ProjectReference Include="..\..\src\Weda.SubNode.Devices\Weda.SubNode.Devices.csproj" />
    <ProjectReference Include="..\..\src\Weda.SubNode.Cloud\Weda.SubNode.Cloud.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
