using Shouldly;
using Weda.SubNode.Abstractions.DigitalTwin;
using Weda.SubNode.Abstractions.Telemetry;
using Xunit;

namespace Weda.SubNode.Core.Tests.DigitalTwin;

/// <summary>
/// Tests for DtdlGenerator auto-generation functionality.
/// </summary>
public class DtdlGeneratorTests
{
    #region GenerateShortId Tests

    [Fact]
    public void GenerateShortId_Should_Return8CharHex()
    {
        // Arrange
        var name = "temperature.sensor";

        // Act
        var shortId = DtdlGenerator.GenerateShortId(name);

        // Assert
        shortId.ShouldNotBeNullOrEmpty();
        shortId.Length.ShouldBe(8);
        shortId.ShouldMatch("^[a-f0-9]{8}$");
    }

    [Fact]
    public void GenerateShortId_Should_BeDeterministic()
    {
        // Arrange
        var name = "channel.0";

        // Act
        var id1 = DtdlGenerator.GenerateShortId(name);
        var id2 = DtdlGenerator.GenerateShortId(name);

        // Assert
        id1.ShouldBe(id2);
    }

    [Fact]
    public void GenerateShortId_Should_BeCaseInsensitive()
    {
        // Arrange & Act
        var lower = DtdlGenerator.GenerateShortId("temperature");
        var upper = DtdlGenerator.GenerateShortId("TEMPERATURE");
        var mixed = DtdlGenerator.GenerateShortId("Temperature");

        // Assert
        lower.ShouldBe(upper);
        lower.ShouldBe(mixed);
    }

    [Fact]
    public void GenerateShortId_Should_ProduceDifferentIdsForDifferentNames()
    {
        // Arrange & Act
        var id1 = DtdlGenerator.GenerateShortId("sensor1");
        var id2 = DtdlGenerator.GenerateShortId("sensor2");

        // Assert
        id1.ShouldNotBe(id2);
    }

    #endregion

    #region GenerateDtmi Tests

    [Fact]
    public void GenerateDtmi_Should_FollowDtmiFormat()
    {
        // Arrange
        var name = "temperature.sensor";

        // Act
        var dtmi = DtdlGenerator.GenerateDtmi(name);

        // Assert
        dtmi.ShouldStartWith("dtmi:autogen:");
        dtmi.ShouldEndWith(";1");
    }

    [Fact]
    public void GenerateDtmi_Should_IncludeNamespaceSegment()
    {
        // Arrange
        var name = "channel.0";
        var namespaceSegment = "AI";

        // Act
        var dtmi = DtdlGenerator.GenerateDtmi(name, namespaceSegment);

        // Assert
        dtmi.ShouldStartWith("dtmi:autogen:ai:");
        dtmi.ShouldEndWith(";1");
    }

    [Fact]
    public void GenerateDtmi_Should_UseSpecifiedVersion()
    {
        // Arrange
        var name = "sensor";
        var version = 2;

        // Act
        var dtmi = DtdlGenerator.GenerateDtmi(name, version: version);

        // Assert
        dtmi.ShouldEndWith(";2");
    }

    [Fact]
    public void GenerateDtmi_Should_SanitizeNamespaceSegment()
    {
        // Arrange
        var name = "sensor";
        var namespaceSegment = "AI_Channel-1";

        // Act
        var dtmi = DtdlGenerator.GenerateDtmi(name, namespaceSegment);

        // Assert
        dtmi.ShouldContain(":aichannel1:");
    }

    #endregion

    #region GenerateTelemetryContent Tests

    [Fact]
    public void GenerateTelemetryContent_Should_CreateValidContent()
    {
        // Arrange
        var sensor = new Sensor
        {
            Name = "temperature.sensor",
            SensorGroup = SensorGroup.TEMP,
            Info = new SensorInfo { Description = "Main temperature reading" }
        };

        // Act
        var content = DtdlGenerator.GenerateTelemetryContent(sensor);

        // Assert
        content.ShouldNotBeNull();
        content.Type.ShouldBe("Telemetry");
        content.Name.ShouldBe("temperature_sensor");
        content.Schema.ShouldBe("double");
        content.Description.ShouldBe("Main temperature reading");
    }

    [Fact]
    public void GenerateTelemetryContent_Should_UseExistingDtmiIfProvided()
    {
        // Arrange
        var existingDtmi = "dtmi:advantech:EdgeSync:Temperature;1";
        var sensor = new Sensor
        {
            Name = "temperature",
            SensorGroup = SensorGroup.TEMP,
            Dtmi = existingDtmi
        };

        // Act
        var content = DtdlGenerator.GenerateTelemetryContent(sensor);

        // Assert
        content.Id.ShouldBe(existingDtmi);
    }

    [Fact]
    public void GenerateTelemetryContent_Should_AutoGenerateDtmiIfMissing()
    {
        // Arrange
        var sensor = new Sensor
        {
            Name = "channel.0",
            SensorGroup = SensorGroup.AI
        };

        // Act
        var content = DtdlGenerator.GenerateTelemetryContent(sensor);

        // Assert
        content.Id.ShouldStartWith("dtmi:autogen:ai:");
        content.Id.ShouldEndWith(";1");
    }

    [Fact]
    public void GenerateTelemetryContent_Should_UseEffectiveSchema()
    {
        // Arrange - AI sensor without explicit schema should use "double"
        var aiSensor = new Sensor { Name = "voltage", SensorGroup = SensorGroup.AI };

        // Arrange - DI sensor without explicit schema should use "boolean"
        var diSensor = new Sensor { Name = "switch", SensorGroup = SensorGroup.DI };

        // Arrange - Sensor with explicit schema
        var customSensor = new Sensor
        {
            Name = "counter",
            SensorGroup = SensorGroup.SYS,
            Info = new SensorInfo { Schema = "integer" }
        };

        // Act
        var aiContent = DtdlGenerator.GenerateTelemetryContent(aiSensor);
        var diContent = DtdlGenerator.GenerateTelemetryContent(diSensor);
        var customContent = DtdlGenerator.GenerateTelemetryContent(customSensor);

        // Assert
        aiContent.Schema.ShouldBe("double");
        diContent.Schema.ShouldBe("boolean");
        customContent.Schema.ShouldBe("integer");
    }

    [Fact]
    public void GenerateTelemetryContent_Should_UseEffectiveDisplayName()
    {
        // Arrange - Sensor without DisplayName should derive from Name
        var sensorWithoutDisplayName = new Sensor
        {
            Name = "temperature.sensor",
            SensorGroup = SensorGroup.TEMP
        };

        // Arrange - Sensor with explicit DisplayName
        var sensorWithDisplayName = new Sensor
        {
            Name = "temp",
            SensorGroup = SensorGroup.TEMP,
            Info = new SensorInfo { DisplayName = "Main Temperature Sensor" }
        };

        // Act
        var content1 = DtdlGenerator.GenerateTelemetryContent(sensorWithoutDisplayName);
        var content2 = DtdlGenerator.GenerateTelemetryContent(sensorWithDisplayName);

        // Assert
        content1.DisplayName.ShouldBe("Temperature Sensor");
        content2.DisplayName.ShouldBe("Main Temperature Sensor");
    }

    [Fact]
    public void GenerateTelemetryContent_Should_SanitizeSensorName()
    {
        // Arrange
        var sensor = new Sensor
        {
            Name = "channel.0",
            SensorGroup = SensorGroup.AI
        };

        // Act
        var content = DtdlGenerator.GenerateTelemetryContent(sensor);

        // Assert
        // DTDL names cannot contain dots, should be replaced with underscores
        content.Name.ShouldBe("channel_0");
    }

    [Fact]
    public void GenerateTelemetryContent_Should_IncludeUnit()
    {
        // Arrange
        var sensor = new Sensor
        {
            Name = "temperature",
            SensorGroup = SensorGroup.TEMP,
            Report = new SensorReport { Unit = "celsius" }
        };

        // Act
        var content = DtdlGenerator.GenerateTelemetryContent(sensor);

        // Assert
        content.Unit.ShouldBe("celsius");
    }

    #endregion

    #region GenerateInterface Tests

    [Fact]
    public void GenerateInterface_Should_CreateValidInterface()
    {
        // Arrange
        var deviceName = "MyModbusDevice";
        var sensors = new List<Sensor>
        {
            new() { Name = "channel.0", SensorGroup = SensorGroup.AI },
            new() { Name = "channel.1", SensorGroup = SensorGroup.AI }
        };

        // Act
        var dtdlInterface = DtdlGenerator.GenerateInterface(deviceName, sensors);

        // Assert
        dtdlInterface.ShouldNotBeNull();
        dtdlInterface.Type.ShouldBe("Interface");
        dtdlInterface.Context.ShouldBe("dtmi:dtdl:context;2");
        dtdlInterface.Id.ShouldStartWith("dtmi:autogen:interface:");
        dtdlInterface.Contents.Count.ShouldBe(2);
    }

    [Fact]
    public void GenerateInterface_Should_UseCustomDisplayNameAndDescription()
    {
        // Arrange
        var deviceName = "WISE-4012";
        var displayName = "WISE-4012 Modbus Device";
        var description = "4-channel analog input device";
        var sensors = new List<Sensor>
        {
            new() { Name = "ch0", SensorGroup = SensorGroup.AI }
        };

        // Act
        var dtdlInterface = DtdlGenerator.GenerateInterface(
            deviceName, sensors, displayName, description);

        // Assert
        dtdlInterface.DisplayName.ShouldBe(displayName);
        dtdlInterface.Description.ShouldBe(description);
    }

    [Fact]
    public void GenerateInterface_Should_GenerateDefaultDisplayNameFromDeviceName()
    {
        // Arrange
        var deviceName = "my_modbus_device";
        var sensors = new List<Sensor>();

        // Act
        var dtdlInterface = DtdlGenerator.GenerateInterface(deviceName, sensors);

        // Assert
        dtdlInterface.DisplayName.ShouldBe("My Modbus Device");
    }

    [Fact]
    public void GenerateInterface_Should_HandleEmptySensorList()
    {
        // Arrange
        var deviceName = "EmptyDevice";
        var sensors = new List<Sensor>();

        // Act
        var dtdlInterface = DtdlGenerator.GenerateInterface(deviceName, sensors);

        // Assert
        dtdlInterface.ShouldNotBeNull();
        dtdlInterface.Contents.ShouldBeEmpty();
    }

    #endregion

    #region PopulateSensorDtmis Tests

    [Fact]
    public void PopulateSensorDtmis_Should_FillEmptyDtmis()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "channel.0", SensorGroup = SensorGroup.AI },
            new() { Name = "channel.1", SensorGroup = SensorGroup.AI, Dtmi = "" },
            new() { Name = "channel.2", SensorGroup = SensorGroup.AI }
        };

        // Act
        DtdlGenerator.PopulateSensorDtmis(sensors);

        // Assert
        sensors[0].Dtmi.ShouldStartWith("dtmi:autogen:ai:");
        sensors[1].Dtmi.ShouldStartWith("dtmi:autogen:ai:");
        sensors[2].Dtmi.ShouldStartWith("dtmi:autogen:ai:");
    }

    [Fact]
    public void PopulateSensorDtmis_Should_PreserveExistingDtmis()
    {
        // Arrange
        var existingDtmi = "dtmi:advantech:EdgeSync:AI;1";
        var sensors = new List<Sensor>
        {
            new() { Name = "channel.0", SensorGroup = SensorGroup.AI, Dtmi = existingDtmi },
            new() { Name = "channel.1", SensorGroup = SensorGroup.AI }
        };

        // Act
        DtdlGenerator.PopulateSensorDtmis(sensors);

        // Assert
        sensors[0].Dtmi.ShouldBe(existingDtmi);
        sensors[1].Dtmi.ShouldStartWith("dtmi:autogen:ai:");
    }

    [Fact]
    public void PopulateSensorDtmis_Should_GenerateDifferentDtmisForDifferentSensors()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "temperature", SensorGroup = SensorGroup.TEMP },
            new() { Name = "humidity", SensorGroup = SensorGroup.TEMP }
        };

        // Act
        DtdlGenerator.PopulateSensorDtmis(sensors);

        // Assert
        sensors[0].Dtmi.ShouldNotBe(sensors[1].Dtmi);
    }

    #endregion

    #region ValidateManualDtdlConfiguration Tests

    [Fact]
    public void ValidateManualDtdlConfiguration_Should_ReturnEmptyForValidConfig()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "ch0", Dtmi = "dtmi:test:sensor1;1" },
            new() { Name = "ch1", Dtmi = "dtmi:test:sensor2;1" }
        };
        var dtdlPath = "dtdl/device.json";

        // Act
        var errors = DtdlGenerator.ValidateManualDtdlConfiguration(sensors, dtdlPath);

        // Assert
        errors.ShouldBeEmpty();
    }

    [Fact]
    public void ValidateManualDtdlConfiguration_Should_ErrorOnMissingDtdlPath()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "ch0", Dtmi = "dtmi:test:sensor1;1" }
        };

        // Act
        var errors = DtdlGenerator.ValidateManualDtdlConfiguration(sensors, null);

        // Assert
        errors.Count.ShouldBe(1);
        errors[0].ShouldContain("DtdlPath is required");
    }

    [Fact]
    public void ValidateManualDtdlConfiguration_Should_ErrorOnEmptyDtdlPath()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "ch0", Dtmi = "dtmi:test:sensor1;1" }
        };

        // Act
        var errors = DtdlGenerator.ValidateManualDtdlConfiguration(sensors, "   ");

        // Assert
        errors.Count.ShouldBe(1);
        errors[0].ShouldContain("DtdlPath is required");
    }

    [Fact]
    public void ValidateManualDtdlConfiguration_Should_ErrorOnMissingSensorDtmi()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "ch0", Dtmi = "dtmi:test:sensor1;1" },
            new() { Name = "ch1" },  // Missing Dtmi
            new() { Name = "ch2", Dtmi = "" }  // Empty Dtmi
        };
        var dtdlPath = "dtdl/device.json";

        // Act
        var errors = DtdlGenerator.ValidateManualDtdlConfiguration(sensors, dtdlPath);

        // Assert
        errors.Count.ShouldBe(2);
        errors.ShouldContain(e => e.Contains("ch1") && e.Contains("missing required Dtmi"));
        errors.ShouldContain(e => e.Contains("ch2") && e.Contains("missing required Dtmi"));
    }

    [Fact]
    public void ValidateManualDtdlConfiguration_Should_ReturnAllErrors()
    {
        // Arrange
        var sensors = new List<Sensor>
        {
            new() { Name = "ch0" },  // Missing Dtmi
            new() { Name = "ch1" }   // Missing Dtmi
        };

        // Act
        var errors = DtdlGenerator.ValidateManualDtdlConfiguration(sensors, null);

        // Assert
        errors.Count.ShouldBe(3);  // 1 for DtdlPath + 2 for sensors
    }

    #endregion

    #region Integration Tests

    [Fact]
    public void FullWorkflow_Should_GenerateCompleteDtdlInterface()
    {
        // Arrange - Simulate a real device configuration
        var deviceName = "WISE-4012";
        var sensors = new List<Sensor>
        {
            new()
            {
                Name = "channel.0",
                SensorGroup = SensorGroup.AI,
                Info = new SensorInfo
                {
                    DisplayName = "Analog Input 0",
                    Description = "First analog input channel"
                },
                Report = new SensorReport { Unit = "mV" }
            },
            new()
            {
                Name = "channel.1",
                SensorGroup = SensorGroup.AI,
                Info = new SensorInfo { DisplayName = "Analog Input 1" }
            },
            new()
            {
                Name = "do.0",
                SensorGroup = SensorGroup.DO,
                Info = new SensorInfo
                {
                    DisplayName = "Digital Output 0",
                    Schema = "boolean"
                }
            }
        };

        // Act - Populate DTMIs first (as would happen in InitializeDtdl)
        DtdlGenerator.PopulateSensorDtmis(sensors);

        // Then generate the interface
        var dtdlInterface = DtdlGenerator.GenerateInterface(
            deviceName,
            sensors,
            description: "WISE-4012 4-channel analog input module");

        // Assert
        dtdlInterface.ShouldNotBeNull();
        dtdlInterface.Context.ShouldBe("dtmi:dtdl:context;2");
        dtdlInterface.Type.ShouldBe("Interface");
        dtdlInterface.Contents.Count.ShouldBe(3);

        // Verify all sensors have DTMIs populated
        foreach (var sensor in sensors)
        {
            sensor.Dtmi.ShouldNotBeNullOrEmpty();
            sensor.Dtmi.ShouldStartWith("dtmi:");
        }

        // Verify content details
        var ch0Content = dtdlInterface.Contents[0];
        ch0Content.Name.ShouldBe("channel_0");
        ch0Content.DisplayName.ShouldBe("Analog Input 0");
        ch0Content.Description.ShouldBe("First analog input channel");
        ch0Content.Schema.ShouldBe("double");
        ch0Content.Unit.ShouldBe("mV");

        var doContent = dtdlInterface.Contents[2];
        doContent.Schema.ShouldBe("boolean");
    }

    #endregion
}
