<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <ProjectReference Include="..\Weda.SubNode.Abstractions\Weda.SubNode.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Client" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Polly.Extensions" />
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="Weda.Dtdl" />
  </ItemGroup>

</Project>
