<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Weda SubNode SDK References -->
  <ItemGroup>
    <ProjectReference Include="../../src/Weda.SubNode.Host/Weda.SubNode.Host.csproj" />
    <ProjectReference Include="../../src/Weda.SubNode.Simulators/Weda.SubNode.Simulators.csproj" />
    <ProjectReference Include="..\..\src\Weda.SubNode.WebApi\Weda.SubNode.WebApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Logging -->
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="systemcfg.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="devicecfg.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="customcfg.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
