<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="NATS.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Weda.SubNode.Abstractions\Weda.SubNode.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Mqtt\SampleImages\*.png" />
  </ItemGroup>

</Project>
